"""从 pyproject 声明追踪当前已验证 Windows 环境，生成固定依赖清单。"""

from __future__ import annotations

import importlib.metadata as metadata
import sys
import tomllib
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "requirements/windows-py312.lock.txt"


def collect_versions(config):
    environment = default_environment()
    initial = (
        config["project"]["dependencies"]
        + config["project"]["optional-dependencies"]["build"]
        + config["project"]["optional-dependencies"]["dev"]
        + config["build-system"]["requires"]
    )
    pending = [(Requirement(item), "") for item in initial]
    expanded = set()
    versions = {}
    while pending:
        requirement, parent_extra = pending.pop()
        if requirement.marker and not requirement.marker.evaluate(
            {**environment, "extra": parent_extra}
        ):
            continue
        name = canonicalize_name(requirement.name)
        installed = metadata.distribution(name)
        if requirement.specifier and not requirement.specifier.contains(
            installed.version, prereleases=True
        ):
            raise RuntimeError(
                f"Installed {name}=={installed.version} does not satisfy {requirement}"
            )
        versions[name] = installed.version
        for extra in {"", *requirement.extras}:
            if (name, extra) in expanded:
                continue
            expanded.add((name, extra))
            pending.extend((Requirement(item), extra) for item in installed.requires or ())
    return versions


def main():
    if sys.platform != "win32" or sys.version_info[:2] != (3, 12):
        raise SystemExit(
            "Generate this lock only from the validated Windows Python 3.12 environment."
        )
    config = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    versions = collect_versions(config)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "# Windows / CPython 3.12; generated by scripts/lock_environment.py.\n"
        "# Source declarations: pyproject.toml. Do not edit package versions here.\n"
        + "".join(f"{name}=={version}\n" for name, version in sorted(versions.items())),
        encoding="utf-8",
    )
    print(f"Recorded {len(versions)} installed dependencies: {OUTPUT}")


if __name__ == "__main__":
    main()
